//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/Domain.Entities")]
    public partial class Book : object
    {
        
        private string AuthorField;
        
        private BookServiceReference.Category CategoryField;
        
        private int CategoryIdField;
        
        private string ISBNField;
        
        private int IdField;
        
        private BookServiceReference.OrderBook[] OrderBooksField;
        
        private decimal PriceField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author
        {
            get
            {
                return this.AuthorField;
            }
            set
            {
                this.AuthorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BookServiceReference.Category Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                this.CategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId
        {
            get
            {
                return this.CategoryIdField;
            }
            set
            {
                this.CategoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN
        {
            get
            {
                return this.ISBNField;
            }
            set
            {
                this.ISBNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BookServiceReference.OrderBook[] OrderBooks
        {
            get
            {
                return this.OrderBooksField;
            }
            set
            {
                this.OrderBooksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/Domain.Entities")]
    public partial class Category : object
    {
        
        private BookServiceReference.Book[] BooksField;
        
        private int IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BookServiceReference.Book[] Books
        {
            get
            {
                return this.BooksField;
            }
            set
            {
                this.BooksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderBook", Namespace="http://schemas.datacontract.org/2004/07/Domain.Entities")]
    public partial class OrderBook : object
    {
        
        private BookServiceReference.Book BookField;
        
        private int BookIdField;
        
        private BookServiceReference.Order OrderField;
        
        private int OrderIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BookServiceReference.Book Book
        {
            get
            {
                return this.BookField;
            }
            set
            {
                this.BookField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookId
        {
            get
            {
                return this.BookIdField;
            }
            set
            {
                this.BookIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BookServiceReference.Order Order
        {
            get
            {
                return this.OrderField;
            }
            set
            {
                this.OrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/Domain.Entities")]
    public partial class Order : object
    {
        
        private BookServiceReference.Customer CustomerField;
        
        private int CustomerIdField;
        
        private int IdField;
        
        private BookServiceReference.OrderBook[] OrderBooksField;
        
        private System.DateTime OrderDateField;
        
        private decimal TotalAmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BookServiceReference.Customer Customer
        {
            get
            {
                return this.CustomerField;
            }
            set
            {
                this.CustomerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId
        {
            get
            {
                return this.CustomerIdField;
            }
            set
            {
                this.CustomerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BookServiceReference.OrderBook[] OrderBooks
        {
            get
            {
                return this.OrderBooksField;
            }
            set
            {
                this.OrderBooksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderDate
        {
            get
            {
                return this.OrderDateField;
            }
            set
            {
                this.OrderDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalAmount
        {
            get
            {
                return this.TotalAmountField;
            }
            set
            {
                this.TotalAmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/Domain.Entities")]
    public partial class Customer : object
    {
        
        private string EmailField;
        
        private string FirstNameField;
        
        private int IdField;
        
        private string LastNameField;
        
        private BookServiceReference.Order[] OrdersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BookServiceReference.Order[] Orders
        {
            get
            {
                return this.OrdersField;
            }
            set
            {
                this.OrdersField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookServiceReference.IBookSoapService")]
    public interface IBookSoapService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookSoapService/GetBooks", ReplyAction="http://tempuri.org/IBookSoapService/GetBooksResponse")]
        System.Threading.Tasks.Task<BookServiceReference.Book[]> GetBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookSoapService/GetBook", ReplyAction="http://tempuri.org/IBookSoapService/GetBookResponse")]
        System.Threading.Tasks.Task<BookServiceReference.Book> GetBookAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookSoapService/GetBookByTitle", ReplyAction="http://tempuri.org/IBookSoapService/GetBookByTitleResponse")]
        System.Threading.Tasks.Task<BookServiceReference.Book> GetBookByTitleAsync(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookSoapService/BookExists", ReplyAction="http://tempuri.org/IBookSoapService/BookExistsResponse")]
        System.Threading.Tasks.Task<bool> BookExistsAsync(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookSoapService/CreateBook", ReplyAction="http://tempuri.org/IBookSoapService/CreateBookResponse")]
        System.Threading.Tasks.Task<bool> CreateBookAsync(int orderId, BookServiceReference.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookSoapService/UpdateBook", ReplyAction="http://tempuri.org/IBookSoapService/UpdateBookResponse")]
        System.Threading.Tasks.Task<bool> UpdateBookAsync(int orderId, BookServiceReference.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookSoapService/DeleteBook", ReplyAction="http://tempuri.org/IBookSoapService/DeleteBookResponse")]
        System.Threading.Tasks.Task<bool> DeleteBookAsync(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookSoapService/Save", ReplyAction="http://tempuri.org/IBookSoapService/SaveResponse")]
        System.Threading.Tasks.Task<bool> SaveAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IBookSoapServiceChannel : BookServiceReference.IBookSoapService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class BookSoapServiceClient : System.ServiceModel.ClientBase<BookServiceReference.IBookSoapService>, BookServiceReference.IBookSoapService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BookSoapServiceClient() : 
                base(BookSoapServiceClient.GetDefaultBinding(), BookSoapServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IBookSoapService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BookSoapServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(BookSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), BookSoapServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BookSoapServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BookSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BookSoapServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BookSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BookSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<BookServiceReference.Book[]> GetBooksAsync()
        {
            return base.Channel.GetBooksAsync();
        }
        
        public System.Threading.Tasks.Task<BookServiceReference.Book> GetBookAsync(int id)
        {
            return base.Channel.GetBookAsync(id);
        }
        
        public System.Threading.Tasks.Task<BookServiceReference.Book> GetBookByTitleAsync(string title)
        {
            return base.Channel.GetBookByTitleAsync(title);
        }
        
        public System.Threading.Tasks.Task<bool> BookExistsAsync(int bookId)
        {
            return base.Channel.BookExistsAsync(bookId);
        }
        
        public System.Threading.Tasks.Task<bool> CreateBookAsync(int orderId, BookServiceReference.Book book)
        {
            return base.Channel.CreateBookAsync(orderId, book);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateBookAsync(int orderId, BookServiceReference.Book book)
        {
            return base.Channel.UpdateBookAsync(orderId, book);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteBookAsync(int bookId)
        {
            return base.Channel.DeleteBookAsync(bookId);
        }
        
        public System.Threading.Tasks.Task<bool> SaveAsync()
        {
            return base.Channel.SaveAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBookSoapService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBookSoapService))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7159/BookSoapService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return BookSoapServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IBookSoapService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return BookSoapServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IBookSoapService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IBookSoapService,
        }
    }
}
